### ISSUE TITLE
Add exception for shared Exoscale SOS buckets

### ISSUE THREAD

**Issue by BostjanBozic** [cscannerio/opensource#39]
# Crash report

- **Cloud provider:** exoscale
- **Rule:** OS_PUBLIC_READ_PROHIBITED

## Stack trace

```
[main] INFO com.opsbears.cscanner.core.ScannerCore - Evaluating rule ObjectStoragePublicReadProhibitedRule with connection test-connection...
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 4a590b33-ed8c-487a-8077-5a77dc75fe2c; S3 Extended Request ID: 4a590b33-ed8c-487a-8077-5a77dc75fe2c), S3 Extended Request ID: 4a590b33-ed8c-487a-8077-5a77dc75fe2c
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
        at com.amazonaws.services.s3.AmazonS3Client.getAcl(AmazonS3Client.java:3887)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectAcl(AmazonS3Client.java:1120)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectAcl(AmazonS3Client.java:1104)
        at com.opsbears.cscanner.objectstorage.S3ObjectStorageClient$ObjectIterator.refillQueue(S3ObjectStorageClient.java:114)
        at com.opsbears.cscanner.objectstorage.S3ObjectStorageClient$ObjectIterator.hasNext(S3ObjectStorageClient.java:136)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.LongPipeline.reduce(LongPipeline.java:461)
        at java.util.stream.LongPipeline.sum(LongPipeline.java:419)
        at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:593)
        at com.opsbears.cscanner.objectstorage.ObjectStoragePublicReadProhibitedRule.lambda$evaluate$4(ObjectStoragePublicReadProhibitedRule.java:90)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at com.opsbears.cscanner.objectstorage.ObjectStoragePublicReadProhibitedRule.evaluate(ObjectStoragePublicReadProhibitedRule.java:111)
        at com.opsbears.cscanner.objectstorage.ObjectStoragePublicReadProhibitedRule.evaluate(ObjectStoragePublicReadProhibitedRule.java:15)
        at com.opsbears.cscanner.core.ScannerCore.scan(ScannerCore.java:138)
        at com.opsbears.cscanner.cli.CLIApplication.run(CLIApplication.java:144)
        at com.opsbears.cscanner.cli.CLIApplication.main(CLIApplication.java:192)
```

## Configuration file

```
connections:
  test-connection:
    type: exoscale
    key: ***
    secret: ***
rules:
  - type: FIREWALL_PUBLIC_SERVICE_PROHIBITED
    protocol: "tcp"
    ports:
      - 22
  - type: OS_PUBLIC_READ_PROHIBITED
    scanContents: true
```

## Cloud account

All list and get permissions on Exoscale are enabled for API key in question.

**Comment by BostjanBozic** [comment]
This could be due to shared buckets between organizations. It would be great to add exception in those cases and list those buckets in report as well as `shared bucket`.
